# Generated by Django 5.2.3 on 2025-06-23 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reglementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre', models.CharField(choices=[('L', 'Lettre L'), ('R', 'Lettre R')], max_length=1)),
                ('numero_article', models.CharField(max_length=10)),
                ('date_version', models.DateField()),
                ('contenu', models.TextField()),
                ('amende', models.TextField(blank=True, null=True)),
                ('retrait_points', models.PositiveIntegerField(default=0)),
                ('autres_sanctions', models.TextField(blank=True, help_text='Ex: annulation, suspension...', null=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglementations', to='themes.theme')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('texte', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='themes/content_images/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='themes.theme')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
