# Generated by Django 5.2.3 on 2026-01-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Nom de la sanction, ex: Suspension de permis', max_length=255)),
                ('duree', models.CharField(blank=True, help_text='Durée de la sanction (ex: 3 ans, 6 mois, définitif)', max_length=100, null=True)),
                ('complementaire', models.BooleanField(default=False, help_text='Cochez si c’est une sanction complémentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes_principaux', to='themes.categorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='themes_tags', to='themes.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Reglementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre', models.CharField(choices=[('L', 'L'), ('R', 'R')], max_length=1)),
                ('numero_article', models.CharField(max_length=10)),
                ('date_version', models.DateField()),
                ('contenu', models.TextField()),
                ('amende', models.TextField(blank=True, null=True)),
                ('retrait_points', models.PositiveIntegerField(default=0)),
                ('sanctions', models.ManyToManyField(blank=True, related_name='reglementations', to='themes.sanction')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglementations', to='themes.theme')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('texte', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='themes/content_images/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='themes.theme')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
