# Generated by Django 5.2.3 on 2025-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('prison_1_an', 'emprisonement de 1 an'), ('prison_2_an', 'emprisonement de 2 an'), ('suspension_3_ans', 'Suspension de permis 3 ans'), ('suspension_3_ans_sans_sursis', 'suspension de permis 3 ans sans sursis'), ('suspenson_5_ans', 'suspension de permis 5 ans'), ('annulation_3_ans', 'Annulation de permis 3 ans'), ('annulation_5_ans', 'annulation de permis 5 ans'), ('annulation_10_ans', 'annulation de permis 10 ans'), ('immobilisation', 'Immobilisation du véhicule'), ('stage_sensibilisation', 'Obligation de suivre un stage de sensibilisation'), ('intediction_conduire_vh', 'interdiction de conduire un véhicule terrestre à moteur'), ('obligation_EAD_5_ans', 'interdiction de condire sans EAD 5 ans'), ('confiscation_vh', 'confiscation du véhicule'), ('peine_TIG', "peine de travail d'intérêt général"), ('peine_jour_amende', 'peine de jour-amende')], max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reglementation',
            name='autres_sanctions',
        ),
        migrations.AddField(
            model_name='reglementation',
            name='sanctions',
            field=models.ManyToManyField(blank=True, null=True, related_name='reglementations', to='themes.sanction'),
        ),
    ]
