# Generated by Django 5.2.3 on 2026-03-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('titre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('titre', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='reglementation',
            name='chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglementations', to='themes.chapitre'),
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='themes.livre')),
            ],
            options={
                'unique_together': {('livre', 'numero')},
            },
        ),
    ]
