# Generated by Django 5.2.3 on 2026-03-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_livre_chapitre_reglementation_chapitre_titre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapitre',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='titre_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='themes.titre'),
        ),
        migrations.AlterUniqueTogether(
            name='chapitre',
            unique_together={('titre_parent', 'numero')},
        ),
    ]
