# Generated by Django 5.2.3 on 2025-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_sanction_remove_reglementation_autres_sanctions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='duree',
            field=models.CharField(blank=True, help_text='Durée de la sanction (ex: 3 ans, 6 mois, définitif)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='libelle',
            field=models.CharField(help_text='Nom de la sanction, ex: Suspension de permis', max_length=255),
        ),
    ]
