# Generated by Django 5.2.3 on 2025-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_sanction_duree_alter_sanction_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='complementaire',
            field=models.BooleanField(default=False, help_text='Cochez si c’est une sanction complémentaire'),
        ),
    ]
