# Generated by Django 5.2.3 on 2025-06-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_sanction_complementaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementation',
            name='lettre',
            field=models.CharField(choices=[('L', 'L'), ('R', 'R')], max_length=1),
        ),
    ]
