# Generated by Django 5.2.3 on 2025-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_alter_reglementation_lettre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='themes', to='themes.categorie'),
        ),
    ]
