# Generated by Django 5.2.3 on 2025-06-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_categorie_theme_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='categories',
        ),
        migrations.AddField(
            model_name='theme',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes_principaux', to='themes.categorie'),
        ),
        migrations.AddField(
            model_name='theme',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='themes_tags', to='themes.categorie'),
        ),
    ]
