# Generated by Django 5.2.3 on 2026-02-09 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('ABORDE', 'Abordé'), ('EN_COURS', 'En cours d’acquisition'), ('ACQUIS', 'Acquis')], default='ABORDE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('ABORDE', 'Abordé'), ('EN_COURS', 'En cours d’acquisition'), ('ACQUIS', 'Acquis')], default='ABORDE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ABORDE', 'Abordé'), ('EN_COURS', 'En cours d’acquisition'), ('ACQUIS', 'Acquis')], default='ABORDE', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_objectifs', to='eleves.eleve')),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleves.objectif')),
            ],
        ),
        migrations.CreateModel(
            name='SousCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('ABORDE', 'Abordé'), ('EN_COURS', 'En cours d’acquisition'), ('ACQUIS', 'Acquis')], default='ABORDE', max_length=20)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_competences', to='eleves.competence')),
            ],
        ),
        migrations.AddField(
            model_name='objectif',
            name='sous_competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='eleves.souscompetence'),
        ),
    ]
