# Generated by Django 5.2.3 on 2025-08-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progression',
            name='heure_cours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
