# Generated by Django 5.2.3 on 2026-02-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_competence_objectif_progressionobjectif_and_more'),
        ('trame_pedagogique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressionobjectif',
            name='objectif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_eleves', to='trame_pedagogique.objectif'),
        ),
        migrations.AlterField(
            model_name='progressionobjectif',
            name='statut',
            field=models.CharField(choices=[('pas_aborde', 'Pas encore abordé'), ('aborde', 'Abordé'), ('en_cours', "En cours d'acquisition"), ('validee', 'Validée')], default='pas_aborde', max_length=20),
        ),
    ]
