# Generated by Django 5.2.3 on 2025-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_progression_heure_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='neph',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
