# Generated by Django 5.2.3 on 2026-02-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(choices=[('C1', 'Compétence 1'), ('C2', 'Compétence 2'), ('C3', 'Compétence 3'), ('C4', 'Compétence 4')], max_length=2, unique=True)),
                ('titre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SousCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre', models.CharField(max_length=1)),
                ('titre', models.CharField(max_length=255)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trame_pedagogique.competence')),
            ],
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('pas_aborde', 'Pas encore abordé'), ('aborde', 'Abordé'), ('en_cours', "En cours d'acquisition"), ('validee', 'Validée')], default='pas_aborde', max_length=20)),
                ('sous_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trame_pedagogique.souscompetence')),
            ],
        ),
    ]
