# Generated by Django 5.2.3 on 2026-01-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('FORMATEUR', 'Formateur'), ('STAGIAIRE', 'Stagiaire'), ('ELEVE', 'Élève')], default='STAGIAIRE', max_length=20),
        ),
    ]
