# Generated by Django 5.2.3 on 2025-12-29 14:14

import mindmap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindmap',
            name='data',
            field=models.JSONField(default=mindmap.models.default_mindmap_data),
        ),
    ]
